services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ADMIN_TOKEN=admin-key-defc40d7
      - DB_CONN_STRING=postgresql://postgres:postgres@postgres:5432/exchange
      - DB_ECHO=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - exchange-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - exchange-network
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - exchange-network
    restart: unless-stopped

  celery:
    build: .
    command: >
      bash -c "pip install -r requirements.txt &&
      celery -A app.tasks.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - DB_CONN_STRING=postgresql://postgres:postgres@postgres:5432/exchange
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - exchange-network
    restart: unless-stopped
    healthcheck:
      test: celery -A app.tasks.celery_app inspect ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  exchange-network:

volumes:
  postgres-data: