services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_CONN_STRING=postgresql://postgres:postgres@db:5432/exchange
      - DB_ECHO=True
    depends_on:
      - db
    networks:
      - exchange-network
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - exchange-network
    restart: unless-stopped

networks:
  exchange-network:

volumes:
  postgres-data: