services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DB_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DB_ECHO=${DB_ECHO:-True}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - exchange-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-6432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - exchange-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    networks:
      - exchange-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  celery:
    build: .
    command: >
      bash -c "pip install -r requirements.txt &&
      celery -A app.tasks.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - DB_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - exchange-network
    restart: unless-stopped
    healthcheck:
      test: celery -A app.tasks.celery_app inspect ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  exchange-network:

volumes:
  postgres-data: